// schema.js — the declarative inspector schema. A field = one Constants.js constant.
//
// Field: { name, label, min, max, step, hint } — a slider with a number (the default);
//   kind: 'color'  — a 0xRRGGBB color (color picker + hex);
//   kind: 'select' + options: [{ value, label }] — a MODE (0/1/2…). Do not make a mode
//         a slider: it has no intermediate values. It stays a number in the file.
// Group: { id, label, fields }. At startup all groups are collapsed.
// Texts (label, hint, option label) — in two languages: { en, ru } (i18n.js).
//
// Ranges are the slider bounds; a value beyond them can still be typed into the numeric field.
// A new constant = a literal in Constants.js + a line here + a read in the code with a default.

// The server contract version this client expects. Must match
// EDITOR_API_VERSION in server.mjs — otherwise the editor warns that editor.bat
// is running old code (Node reads server files only at process start).
const EDITOR_API_VERSION = 21;

// Ink edges and outline levels: 0 — off, 1 — main objects (actor), 2 — and environment (prop).
const SCHEMA_LEVELS = [
    { value: 0, label: { en: 'off', ru: 'нет' } },
    { value: 1, label: { en: 'main objects', ru: 'главные объекты' } },
    { value: 2, label: { en: 'main + environment', ru: 'и окружение' } },
];
const SCHEMA_NO_YES = [
    { value: 0, label: { en: 'no', ru: 'нет' } },
    { value: 1, label: { en: 'yes', ru: 'да' } },
];

const KIT_SCHEMA = [
    {
        id: 'camera',
        label: { en: 'Camera', ru: 'Камера' },
        fields: [
            { name: 'CAMERA_FOV_DEG', min: 20, max: 100, step: 1,
              label: { en: 'Field of view (°)', ru: 'Угол обзора (°)' },
              hint: { en: 'Vertical FOV. Scale at the look-at point comes from zoom, not FOV: a narrower angle means less perspective',
                      ru: 'Вертикальный FOV. Масштаб в точке взгляда задаёт зум, не FOV: меньше угол — меньше перспективы' } },
            { name: 'CAMERA_AZIMUTH_DEG', min: -180, max: 180, step: 5,
              label: { en: 'Heading (°)', ru: 'Ориентация (°)' },
              hint: { en: 'Where the camera looks on the map: −90 is north-up, 0 is east-up. Applied on camera reset (R)',
                      ru: 'Куда смотрит камера по карте: −90 — север вверх, 0 — восток вверх. Применяется при сбросе камеры (R)' } },
            { name: 'CAMERA_PITCH_DEG', min: 20, max: 90, step: 1,
              label: { en: 'Pitch (°)', ru: 'Наклон к земле (°)' },
              hint: { en: '90 is straight down; lower adds depth and perspective. Applied on camera reset (R)',
                      ru: '90 — строго сверху, меньше — больше объёма и перспективы. Применяется при сбросе камеры (R)' } },
            { name: 'CAMERA_ZOOM', min: 0.2, max: 4, step: 0.05,
              label: { en: 'Start zoom: desktop', ru: 'Стартовый зум: ПК' },
              hint: { en: 'Screen px per world px at the look-at point, at launch and on reset (R)',
                      ru: 'Экранных px на мировой px в точке взгляда при запуске и сбросе (R)' } },
            { name: 'CAMERA_ZOOM_MOBILE', min: 0.2, max: 4, step: 0.05,
              label: { en: 'Start zoom: phones', ru: 'Стартовый зум: телефоны' },
              hint: { en: 'Screens whose longer side is under 1024 px',
                      ru: 'Экраны, у которых большая сторона короче 1024 px' } },
            { name: 'CAMERA_ZOOM_MIN', min: 0.1, max: 4, step: 0.05,
              label: { en: 'Zoom: farthest', ru: 'Зум: дальше не отводится' },
              hint: { en: 'Wheel and pinch limit in the game. Too far and the ground edge beyond the location comes into view (pitch rises by itself, but not above its limit)',
                      ru: 'Предел колеса и щипка в игре. Слишком далеко — в кадр попадёт край земли за локацией (наклон поднимется сам, но не выше предела)' } },
            { name: 'CAMERA_ZOOM_MAX', min: 0.2, max: 8, step: 0.05,
              label: { en: 'Zoom: closest', ru: 'Зум: ближе не приближается' } },
            { name: 'CAMERA_ZOOM_WHEEL_STEP', min: 0.02, max: 0.5, step: 0.01,
              label: { en: 'Wheel step (fraction)', ru: 'Шаг колеса (доля)' },
              hint: { en: '0.12 = ±12% zoom per wheel notch', ru: '0.12 = ±12% зума за щелчок' } },
            { name: 'CAMERA_ZOOM_LERP', min: 0.02, max: 1, step: 0.02,
              label: { en: 'Zoom smoothing', ru: 'Сглаживание зума' },
              hint: { en: 'Fraction of the remaining gap per frame (1 is instant)', ru: 'Доля остатка за кадр (1 — мгновенно)' } },
            { name: 'CAMERA_FOLLOW_LERP', min: 0.01, max: 1, step: 0.01,
              label: { en: 'Follow smoothing', ru: 'Сглаживание слежения' },
              hint: { en: 'camera.follow(obj): fraction of the remaining gap per frame', ru: 'camera.follow(obj): доля остатка за кадр' } },
            { name: 'CAMERA_FLY_SPEED', min: 100, max: 3000, step: 50,
              label: { en: 'Flight speed (screen px/s)', ru: 'Скорость полёта (экранных px/с)' },
              hint: { en: 'WASD and arrows fly along the view and strafe, Q/E go down/up. Set in screen px: zoomed out, the camera covers more of the world per second',
                      ru: 'WASD и стрелки — полёт вдоль взгляда и вбок, Q/E — вниз/вверх. Задаётся в экранных px: при отдалении камера проходит по миру больше' } },
            { name: 'CAMERA_LIMITS', kind: 'select', options: SCHEMA_NO_YES,
              label: { en: 'Game camera limits', ru: 'Пределы игровой камеры' },
              hint: { en: "No — free flight, as in the editor's free camera. Yes — pitch within its limits, target inside the location, flight ceiling: the ground edge beyond the location never comes into view",
                      ru: 'Нет — свободный полёт, как у свободной камеры редактора. Да — наклон в своих пределах, цель внутри локации, потолок полёта: край земли за локацией в кадр не попадает' } },
            { name: 'CAMERA_LIFT_MAX', min: 0, max: 3000, step: 50,
              label: { en: 'Limits: flight ceiling (px)', ru: 'Пределы: потолок полёта (px)' },
              hint: { en: 'How high above the ground flight lifts the look-at point. Too high and the ground edge beyond the location comes into view',
                      ru: 'Как высоко над землёй полёт поднимает точку взгляда. Слишком высоко — в кадр попадёт край земли за локацией' } },
            { name: 'CAMERA_ORBIT', kind: 'select',
              label: { en: 'Player rotation', ru: 'Вращение игроком' },
              options: [
                  { value: 0, label: { en: 'off — heading fixed', ru: 'нет — ориентация фиксирована' } },
                  { value: 1, label: { en: 'RMB rotates', ru: 'ПКМ вращает' } },
              ],
              hint: { en: "Game camera: whether the right mouse button rotates it — look-around from the camera's position, orbit while it follows an object. The editor's free camera always rotates",
                      ru: 'Игровая камера: можно ли крутить её правой кнопкой — осмотр с места камеры, при слежении за объектом — орбита вокруг него. Свободная камера редактора вращается всегда' } },
            { name: 'CAMERA_ORBIT_DEG_PER_PX', min: 0.05, max: 1, step: 0.05,
              label: { en: 'Rotation speed (°/px)', ru: 'Скорость вращения (°/px)' } },
            { name: 'CAMERA_ORBIT_PITCH_MIN_DEG', min: 5, max: 89, step: 1,
              label: { en: 'Limits: lowest pitch (°)', ru: 'Пределы: наклон не ниже (°)' },
              hint: { en: 'The limit also rises by itself: the ground edge beyond the location never comes into view',
                      ru: 'Предел поднимается и сам: край земли за локацией в кадр не попадает' } },
            { name: 'CAMERA_ORBIT_PITCH_MAX_DEG', min: 20, max: 89, step: 1,
              label: { en: 'Limits: highest pitch (°)', ru: 'Пределы: наклон не выше (°)' },
              hint: { en: 'Close to 90 is straight down', ru: 'Почти 90 — строго сверху' } },
        ],
    },
    {
        id: 'toon',
        label: { en: 'Toon shader', ru: 'Toon-шейдер' },
        fields: [
            { name: 'WORLD3D_TOON', kind: 'select',
              label: { en: 'Shading', ru: 'Затенение' },
              options: [
                  { value: 0, label: { en: 'smooth', ru: 'плавное' } },
                  { value: 1, label: { en: 'toon (bands)', ru: 'toon (ступени)' } },
              ],
              hint: { en: 'Light from all sources (sun + sky, with shadow) is quantized into bands. 0 is regular smooth shading without the silhouette outline',
                      ru: 'Свет всех источников (солнце + небо, с тенью) квантуется в ступени. 0 — обычное плавное затенение без обводки силуэта' } },
            { name: 'WORLD3D_TOON_BANDS', min: 2, max: 6, step: 1,
              label: { en: 'Light bands', ru: 'Ступеней света' },
              hint: { en: '2 is light/shadow, 3 is light/half-tone/shadow…', ru: '2 — свет/тень, 3 — свет/полутень/тень…' } },
            { name: 'WORLD3D_TOON_SOFT', min: 0, max: 0.5, step: 0.01,
              label: { en: 'Band edge softness', ru: 'Мягкость границ' },
              hint: { en: '0 is a hard step between bands, 0.5 is almost smooth', ru: '0 — резкий переход между ступенями, 0.5 — почти плавный' } },
            { name: 'WORLD3D_TOON_LOW', min: 0, max: 0.9, step: 0.01,
              label: { en: 'Darkest band', ru: 'Тёмная ступень' },
              hint: { en: 'Brightness of the darkest band (fraction of full). For shadows to land in their own band, keep it below 1 − shadow strength',
                      ru: 'Яркость самой тёмной ступени (доля от полной). Чтобы тень попадала в свою ступень, держите её ниже 1 − «сила тени»' } },
            { name: 'WORLD3D_TOON_GROUND', kind: 'select', options: SCHEMA_NO_YES,
              label: { en: 'Bands on the ground', ru: 'Ступени на земле' },
              hint: { en: '0 shades the ground smoothly, bands stay on objects only', ru: '0 — земля затеняется плавно, ступени только на объектах' } },
            { name: 'WORLD3D_TOON_SPEC', min: 0, max: 3, step: 0.05,
              label: { en: 'Specular spot', ru: 'Блик-«зайчик»' },
              hint: { en: 'Strength of the flat highlight. Visible only if the material group has specular (Materials group)',
                      ru: 'Сила плоского блика. Виден, только если у материала группы есть блик (группа «Материалы»)' } },
            { name: 'WORLD3D_TOON_SPEC_SIZE', min: 0.01, max: 0.4, step: 0.005,
              label: { en: 'Specular threshold', ru: 'Порог блика' },
              hint: { en: 'Lower gives a bigger highlight spot', ru: 'Меньше — пятно блика крупнее' } },
            { name: 'WORLD3D_TOON_RIM', min: 0, max: 1, step: 0.02,
              label: { en: 'Rim light', ru: 'Ободок силуэта' },
              hint: { en: 'Light edge along object silhouettes (fresnel), fades in shadow. 0 is off',
                      ru: 'Светлая кромка по краю объектов (fresnel), гаснет в тени. 0 — нет' } },
            { name: 'WORLD3D_TOON_RIM_WIDTH', min: 0.05, max: 0.9, step: 0.01,
              label: { en: 'Rim width', ru: 'Ширина ободка' } },
        ],
    },
    {
        id: 'ink',
        label: { en: 'Edges and outline', ru: 'Контур и обводка' },
        fields: [
            { name: 'WORLD3D_TOON_OUTLINE', kind: 'select', options: SCHEMA_LEVELS,
              label: { en: 'Silhouette outline', ru: 'Обводка силуэта' },
              hint: { en: 'A line along the OUTER border of an object, like Stroke in Photoshop: the object mask is dilated by a post effect and laid over the frame. Part of the toon look: with smooth shading there is no outline. Color — "Ink color" below',
                      ru: 'Линия по ВНЕШНЕЙ границе объекта, как Stroke в фотошопе: маска расширяется постэффектом и накладывается на кадр. Часть toon-вида: при плавном затенении обводки нет. Цвет — «Цвет чернил» ниже' } },
            { name: 'WORLD3D_TOON_OUTLINE_ACTOR_WIDTH', min: 0, max: 12, step: 0.5,
              label: { en: 'Outline width: main (screen px)', ru: 'Толщина обводки: главные (экранных px)' },
              hint: { en: 'Independent of camera distance. Main objects are the actor group (World3D.addObject)',
                      ru: 'Не зависит от расстояния до камеры. Главные объекты — группа actor (World3D.addObject)' } },
            { name: 'WORLD3D_TOON_OUTLINE_PROP_WIDTH', min: 0, max: 12, step: 0.5,
              label: { en: 'Outline width: environment (screen px)', ru: 'Толщина обводки: окружение (экранных px)' },
              hint: { en: 'Environment is the prop group. There is a lot of it in the frame, so the line is usually thinner; 0 turns it off',
                      ru: 'Окружение — группа prop. Его в кадре много, поэтому линия обычно тоньше; 0 — без обводки' } },
            { name: 'WORLD3D_TOON_INK', kind: 'select', options: SCHEMA_LEVELS,
              label: { en: 'Edge lines', ru: 'Контур рёбер' },
              hint: { en: 'Edges of lowpoly models sharper than the threshold get a line (EdgesRenderer). These are ALL such edges, inner ones included',
                      ru: 'Рёбра lowpoly-моделей, изломанные круче порога, обводятся линией (EdgesRenderer). Это ВСЕ такие рёбра, включая внутренние' } },
            { name: 'WORLD3D_TOON_INK_WIDTH', min: 5, max: 400, step: 5,
              label: { en: 'Edge line width', ru: 'Толщина линии рёбер' },
              hint: { en: '≈ world px × 100: the line thins as the camera moves away, like ink on the model',
                      ru: '≈ мировых px × 100: линия тоньше при отдалении камеры, как чернила на модели' } },
            { name: 'WORLD3D_TOON_INK_COLOR', kind: 'color',
              label: { en: 'Ink color', ru: 'Цвет чернил' },
              hint: { en: 'Shared by edge lines and the silhouette outline', ru: 'Один на контур рёбер и обводку силуэта' } },
            { name: 'WORLD3D_TOON_INK_ANGLE', min: 5, max: 89, step: 1,
              label: { en: 'Crease threshold (°)', ru: 'Порог излома (°)' },
              hint: { en: 'An edge is drawn if its faces meet at a sharper angle; lower draws more lines',
                      ru: 'Ребро рисуется, если грани изломаны круче; меньше — больше линий' } },
        ],
    },
    {
        id: 'shadow',
        label: { en: 'Shadows', ru: 'Тени' },
        fields: [
            { name: 'WORLD3D_SHADOW_COLOR', kind: 'color',
              label: { en: 'Shadow color', ru: 'Цвет тени' },
              hint: { en: 'ONE for all shadows. A surface in shadow is multiplied by a mix of white and this color by strength',
                      ru: 'ОДИН на все тени. Поверхность в тени умножается на смесь белого и этого цвета по силе' } },
            { name: 'WORLD3D_SHADOW_STRENGTH', min: 0, max: 1, step: 0.02,
              label: { en: 'Shadow strength', ru: 'Сила тени' },
              hint: { en: '0 means no shadows, 1 multiplies the shaded surface by the full shadow color',
                      ru: '0 — теней нет, 1 — поверхность в тени умножена на цвет тени целиком' } },
            { name: 'WORLD3D_SHADOW_SOFT', kind: 'select',
              label: { en: 'Shadow edge', ru: 'Край тени' },
              options: [
                  { value: 0, label: { en: 'hard', ru: 'жёсткий' } },
                  { value: 1, label: { en: 'PCF low', ru: 'PCF низкое' } },
                  { value: 2, label: { en: 'PCF medium', ru: 'PCF среднее' } },
                  { value: 3, label: { en: 'PCF high', ru: 'PCF высокое' } },
              ],
              hint: { en: '0 is hard (suits toon), 1..3 is the filtering quality. Phones: at most 1',
                      ru: '0 — жёсткий (под toon), 1..3 — качество сглаживания. Мобильные — не выше 1' } },
            { name: 'WORLD3D_SHADOW_MAP', min: 512, max: 4096, step: 512,
              label: { en: 'Shadow map (px)', ru: 'Карта теней (px)' },
              hint: { en: 'Shadow map resolution (half on phones). Takes effect after reloading the page',
                      ru: 'Разрешение карты теней (мобильные — вдвое меньше). Действует после перезагрузки страницы' } },
            { name: 'WORLD3D_SHADOW_RADIUS', min: 300, max: 1600, step: 20,
              label: { en: 'Shadow frame (px)', ru: 'Кадр теней (px)' },
              hint: { en: "Max half-size of the sun's ortho frame around the camera target: wider keeps shadows farther from the center, but coarser. Takes effect after reload",
                      ru: 'Предел полуразмера ортокадра солнца вокруг цели камеры: шире — тени дальше от центра, но грубее. Действует после перезагрузки' } },
            { name: 'WORLD3D_SHADOW_BIAS', min: 0, max: 0.005, step: 0.0001,
              label: { en: 'Depth bias', ru: 'Смещение глубины' },
              hint: { en: 'Fights shadow acne — shadow stripes on lit faces. Too much detaches the shadow from the object',
                      ru: 'Против «акне» — полос тени на освещённых гранях. Слишком много — тень отрывается от предмета' } },
            { name: 'WORLD3D_SHADOW_NORMAL_BIAS', min: 0, max: 4, step: 0.1,
              label: { en: 'Normal bias (texels)', ru: 'Смещение по нормали (тексели)' },
              hint: { en: 'Fights shadow acne on faces at a grazing angle to the sun (stripes, sawtooth). In shadow map texels on top of the shadow edge filter radius, which the engine adds itself, so it follows the shadow frame size and the edge softness. Too much makes thin parts lose their shadow',
                      ru: 'Против «акне» на гранях под острым углом к солнцу (полосы, «пила»). В текселях карты теней сверх радиуса сглаживания края — его движок прибавляет сам, так что значение следует за размером кадра и мягкостью края. Слишком много — тонкие детали теряют тень' } },
        ],
    },
    {
        id: 'sky',
        label: { en: 'Sky and fog', ru: 'Небо и туман' },
        fields: [
            { name: 'WORLD3D_SKY_COLOR', kind: 'color',
              label: { en: 'Sky and fog color', ru: 'Цвет неба и тумана' } },
            { name: 'WORLD3D_FOG_DENSITY', min: 0, max: 0.002, step: 0.00005,
              label: { en: 'Fog', ru: 'Туман' },
              hint: { en: 'Exponential fog towards the horizon; 0 turns it off', ru: 'Экспоненциальный туман к горизонту; 0 — выключить' } },
        ],
    },
    {
        id: 'materials',
        label: { en: 'Materials', ru: 'Материалы' },
        fields: [
            { name: 'WORLD3D_GROUND_SPECULAR', min: 0, max: 0.5, step: 0.01,
              label: { en: 'Ground specular', ru: 'Блик земли' },
              hint: { en: '0 is matte', ru: '0 — матовая' } },
            { name: 'WORLD3D_GROUND_SPEC_POWER', min: 1, max: 128, step: 1,
              label: { en: 'Ground specular size', ru: 'Размер блика земли' },
              hint: { en: 'Exponent: higher gives a smaller, sharper highlight', ru: 'Показатель степени: больше — блик мельче и резче' } },
            { name: 'WORLD3D_OUTER_TINT', min: 0.3, max: 1.3, step: 0.02,
              label: { en: 'Ground brightness beyond the location', ru: 'Яркость земли за краем локации' },
              hint: { en: '1 matches the inside; lower makes the location border visible', ru: '1 — как внутри; меньше — граница локации видна' } },
            { name: 'WORLD3D_PROP_SPECULAR', min: 0, max: 1, step: 0.01,
              label: { en: 'Environment specular', ru: 'Блик окружения' },
              hint: { en: 'prop group: boxes, walls, trees', ru: 'Группа prop: кубы, стены, деревья' } },
            { name: 'WORLD3D_PROP_SPEC_POWER', min: 1, max: 128, step: 1,
              label: { en: 'Environment specular size', ru: 'Размер блика окружения' } },
            { name: 'WORLD3D_ACTOR_SPECULAR', min: 0, max: 1, step: 0.01,
              label: { en: 'Main object specular', ru: 'Блик главных объектов' },
              hint: { en: 'actor group: characters, vehicles. With toon — brightness of the specular spot',
                      ru: 'Группа actor: персонажи, машины. Под toon — яркость «зайчика»' } },
            { name: 'WORLD3D_ACTOR_SPEC_POWER', min: 1, max: 128, step: 1,
              label: { en: 'Main object specular size', ru: 'Размер блика главных объектов' } },
        ],
    },
    {
        id: 'location',
        label: { en: 'Location and terrain', ru: 'Локация и рельеф' },
        fields: [
            { name: 'LOCATION_WIDTH', min: 256, max: 8192, step: 64,
              label: { en: 'Location width (px)', ru: 'Ширина локации (px)' },
              hint: { en: 'The game camera keeps its target inside the location', ru: 'Игровая камера держит цель внутри локации' } },
            { name: 'LOCATION_HEIGHT', min: 256, max: 8192, step: 64,
              label: { en: 'Location height (px)', ru: 'Высота локации (px)' } },
            { name: 'LOCATION_GROUND', kind: 'select',
              label: { en: 'Ground texture', ru: 'Текстура земли' },
              options: [
                  { value: 0, label: { en: 'grass', ru: 'трава' } },
                  { value: 1, label: { en: 'sand', ru: 'песок' } },
                  { value: 2, label: { en: 'snow', ru: 'снег' } },
              ] },
            { name: 'GROUND_TILE_SIZE', min: 64, max: 2048, step: 16,
              label: { en: 'Texture tile (px)', ru: 'Повтор текстуры (px)' },
              hint: { en: 'World px covered by one texture tile', ru: 'Сколько мировых px занимает один тайл текстуры' } },
            { name: 'TERRAIN_NOISE_AMP', min: 0, max: 200, step: 2,
              label: { en: 'Hill height (px)', ru: 'Высота холмов (px)' },
              hint: { en: '0 is flat ground', ru: '0 — плоская земля' } },
            { name: 'TERRAIN_NOISE_SCALE', min: 60, max: 3000, step: 20,
              label: { en: 'Hill size (px)', ru: 'Размер холма (px)' } },
            { name: 'TERRAIN_NOISE_SEED', min: 0, max: 99999, step: 1,
              label: { en: 'Terrain seed', ru: 'Сид рельефа' } },
            { name: 'TERRAIN_BASE', min: -200, max: 200, step: 2,
              label: { en: 'Ground level (px)', ru: 'Уровень земли (px)' } },
            { name: 'TERRAIN_CELL', min: 4, max: 64, step: 1,
              label: { en: 'Grid cell (px)', ru: 'Шаг сетки (px)' },
              hint: { en: 'Smaller gives smoother hills and a heavier mesh (phones: no finer than 12)',
                      ru: 'Мельче — глаже холмы, тяжелее меш (мобильные — не мельче 12)' } },
        ],
    },
    {
        id: 'models',
        label: { en: 'Models, UI and sample game', ru: 'Модели, UI и пример игры' },
        fields: [
            { name: 'MODEL_BOT_MOVE_THRESHOLD', min: 0, max: 10, step: 0.5,
              label: { en: 'Bot motion threshold', ru: 'Порог движения ботов' } },
            { name: 'MODEL_BOT_STRIDE', min: 5, max: 100, step: 1,
              label: { en: 'Bot stride (cm)', ru: 'Шаг ботов (см)' } },
            { name: 'MODEL_CLIP_BLEND_SEC', min: 0, max: 1, step: 0.05,
              label: { en: 'Clip cross-fade (s)', ru: 'Переход между клипами (с)' },
              hint: { en: 'How long a .glb model blends from one animation clip to the next (idle → run). 0 switches instantly',
                      ru: 'За сколько .glb-модель перетекает из одного клипа анимации в другой (idle → run). 0 — мгновенно' } },
            { name: 'UI_REF_HEIGHT', min: 0, max: 2160, step: 10,
              label: { en: 'UI reference height (px)', ru: 'Опорная высота UI (px)' },
              hint: { en: 'The screen height the UI layout is drawn for: on other screens the whole UI scales with the height. 0 — no scaling, layout numbers are CSS px',
                      ru: 'Высота экрана, под которую нарисован UI: на других экранах весь UI масштабируется по высоте. 0 — без масштаба, числа раскладки — CSS px' } },
            { name: 'GAME_PLAYER_SPEED', min: 80, max: 600, step: 10,
              label: { en: 'Player speed', ru: 'Скорость игрока' } },
            { name: 'GAME_PLAYER_RADIUS', min: 8, max: 60, step: 1,
              label: { en: 'Player collision radius', ru: 'Радиус коллизии игрока' } },
            { name: 'GAME_PLAYER_HP', min: 10, max: 300, step: 5,
              label: { en: 'Player health', ru: 'Здоровье игрока' } },
            { name: 'GAME_FIRE_INTERVAL', min: 0.05, max: 1, step: 0.01,
              label: { en: 'Fire interval (s)', ru: 'Интервал выстрелов (с)' } },
            { name: 'GAME_FIRE_DAMAGE', min: 1, max: 200, step: 1,
              label: { en: 'Weapon damage', ru: 'Урон оружия' } },
            { name: 'GAME_FIRE_RANGE', min: 100, max: 2000, step: 25,
              label: { en: 'Weapon range', ru: 'Дальность оружия' } },
            { name: 'GAME_IMPACT_AUDIO_RANGE', min: 200, max: 4000, step: 100,
              label: { en: 'Impact audible range', ru: 'Слышимость попаданий' } },
            { name: 'GAME_WHIZ_AUDIO_RANGE', min: 200, max: 3000, step: 100,
              label: { en: 'Near-miss whiz range', ru: 'Слышимость пролёта пули' } },
            { name: 'GAME_RICOCHET_AUDIO_RANGE', min: 200, max: 4000, step: 100,
              label: { en: 'Ricochet audible range', ru: 'Слышимость рикошета' } },
            { name: 'GAME_SHOT_AUDIO_RANGE', min: 500, max: 8192, step: 100,
              label: { en: 'Gunfire audible range', ru: 'Слышимость выстрелов' } },
            { name: 'GAME_FIRE_SPREAD_DEG', min: 0, max: 10, step: 0.1,
              label: { en: 'Hip-fire spread (°)', ru: 'Разброс от бедра (°)' } },
            { name: 'GAME_ADS_FOV_DEG', min: 20, max: 70, step: 1,
              label: { en: 'Aiming field of view', ru: 'Угол обзора в прицеле' } },
            { name: 'GAME_MAG_SIZE', min: 1, max: 100, step: 1,
              label: { en: 'Magazine size', ru: 'Ёмкость магазина' } },
            { name: 'GAME_RESERVE_AMMO', min: 0, max: 300, step: 10,
              label: { en: 'Starting reserve ammo', ru: 'Стартовый запас патронов' } },
            { name: 'GAME_RELOAD_SEC', min: 0.2, max: 8, step: 0.1,
              label: { en: 'Reload time (s)', ru: 'Время перезарядки (с)' } },
            { name: 'GAME_MEDKIT_HEAL', min: 5, max: 100, step: 5,
              label: { en: 'Medkit healing', ru: 'Лечение аптечкой' } },
            { name: 'GAME_HEAL_SEC', min: 0.5, max: 10, step: 0.1,
              label: { en: 'Healing time (s)', ru: 'Время лечения (с)' } },
            { name: 'GAME_STAMINA_MAX', min: 30, max: 300, step: 5,
              label: { en: 'Maximum stamina', ru: 'Максимум выносливости' } },
            { name: 'GAME_STAMINA_DRAIN', min: 1, max: 100, step: 1,
              label: { en: 'Sprint stamina per second', ru: 'Расход выносливости в секунду' } },
            { name: 'GAME_STAMINA_REGEN', min: 1, max: 100, step: 1,
              label: { en: 'Stamina recovery per second', ru: 'Восстановление выносливости в секунду' } },
            { name: 'GAME_STAMINA_DELAY', min: 0, max: 5, step: 0.1,
              label: { en: 'Stamina recovery delay', ru: 'Задержка восстановления выносливости' } },
            { name: 'GAME_STAMINA_RESTART', min: 1, max: 30, step: 1,
              label: { en: 'Stamina to resume sprinting', ru: 'Выносливость для повторного спринта' } },
            { name: 'GAME_NOISE_SHOT', min: 100, max: 2000, step: 10,
              label: { en: 'Gunshot hearing range', ru: 'Дальность слышимости выстрела' } },
            { name: 'GAME_NOISE_SPRINT', min: 0, max: 1000, step: 10,
              label: { en: 'Sprint hearing range', ru: 'Дальность слышимости бега' } },
            { name: 'GAME_NOISE_WALK', min: 0, max: 500, step: 10,
              label: { en: 'Walk hearing range', ru: 'Дальность слышимости шагов' } },
            { name: 'GAME_INTERACT_RANGE', min: 40, max: 150, step: 5,
              label: { en: 'Interaction range', ru: 'Дальность взаимодействия' } },
            { name: 'GAME_BACKPACK_SLOTS', min: 1, max: 24, step: 1,
              label: { en: 'Backpack capacity', ru: 'Вместимость рюкзака' } },
            { name: 'GAME_RESERVE_CAPACITY', min: 120, max: 300, step: 10,
              label: { en: 'Reserve ammo capacity', ru: 'Вместимость запаса патронов' } },
            { name: 'GAME_MEDKIT_CAPACITY', min: 4, max: 10, step: 1,
              label: { en: 'Medkit capacity', ru: 'Вместимость аптечек' } },
            { name: 'GAME_SEARCH_SEC', min: 0.2, max: 5, step: 0.1,
              label: { en: 'Container search time (s)', ru: 'Время обыска контейнера (с)' } },
            { name: 'GAME_ENEMY_COUNT', min: 1, max: 30, step: 1,
              label: { en: 'Enemy count', ru: 'Количество противников' } },
            { name: 'GAME_ENEMY_SPEED', min: 20, max: 400, step: 5,
              label: { en: 'Enemy speed', ru: 'Скорость противника' } },
            { name: 'GAME_ENEMY_HP', min: 10, max: 300, step: 5,
              label: { en: 'Enemy health', ru: 'Здоровье противника' } },
            { name: 'GAME_ENEMY_AGGRO', min: 100, max: 1500, step: 20,
              label: { en: 'Enemy detection radius', ru: 'Радиус обнаружения' } },
            { name: 'GAME_ENEMY_DAMAGE', min: 1, max: 100, step: 1,
              label: { en: 'Enemy damage', ru: 'Урон противника' } },
            { name: 'GAME_ENEMY_ATTACK_SEC', min: 0.1, max: 5, step: 0.1,
              label: { en: 'Enemy attack interval', ru: 'Интервал атак противника' } },
            { name: 'GAME_LOOT_TARGET', min: 1, max: 10, step: 1,
              label: { en: 'Required data drives', ru: 'Нужно накопителей данных' } },
            { name: 'GAME_EXTRACT_INBOUND_SEC', min: 1, max: 60, step: 1,
              label: { en: 'Transport arrival time', ru: 'Время прибытия транспорта' } },
            { name: 'GAME_EXTRACT_SEC', min: 1, max: 30, step: 0.5,
              label: { en: 'Extraction time', ru: 'Время эвакуации' } },
        ],
    },
];

// Objects panel schema: the OPTIONAL fields of a LOCATION_OBJECTS record (Objects.js).
// Unlike KIT_SCHEMA these are not Constants.js numbers — they are the fields the objects
// panel edits on the selected record. Absent or empty means the field is not written
// (save.mjs formatObjects drops it), so an entry here is a field a designer MAY fill in.
// kind: 'text' — a string field, 'flag' — a checkbox. The required record fields (name,
// model, kind, x, y, h, rot, scale) are always written and are not listed.
const OBJECT_OPTIONAL_FIELDS = [
    { name: 'tag', kind: 'text',
      label: { en: 'Tag', ru: 'Тег' },
      hint: { en: 'A group name for game code: location.findByTag(tag) returns every object with it — extraction points, bosses, loot crates. Empty — the object belongs to no group',
              ru: 'Имя группы для кода игры: location.findByTag(tag) вернёт все объекты с ним — точки эвакуации, боссы, ящики с добычей. Пусто — объект ни в одной группе' } },
    { name: 'hidden', kind: 'flag',
      label: { en: 'Hidden', ru: 'Скрыт' },
      hint: { en: 'Placed but out of the scene (disabled, children included) until the game calls location.setHidden(rec, false) — a boss or a bridge revealed by an event. The editor shows it as a ghost',
              ru: 'Расставлен, но в сцене его нет (выключен вместе с детьми), пока игра не вызовет location.setHidden(rec, false) — босс или мост, который открывает событие. В редакторе виден призраком' } },
];
